# Config file for automatic testing at travis-ci.com
language: python
python:
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_dev.txt
script:
- pytest --ignore tests/test_download.py

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bw4sz
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: bw4sz/neontreeevaluation_python
    python: 3.8
