name: NeonTreeEvaluation
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas
  - descartes
  - rtree
  - pandas
  - pytest
  - numpy
  - matplotlib
  - rasterio
  - shapely
  - scipy
  - pip
  - pip:
    - pandas_read_xml
    - bump2version
